{
 "title": "Jitsi Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "bit_rate_download",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"bit_rate_download\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bit_rate_download" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "bit_rate_upload",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"bit_rate_download\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bit_rate_upload" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "conferences",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"bit_rate_download\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "conferences" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "endpoints_sending_audio",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"endpoints_sending_audio\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "endpoints_sending_audio" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "endpoints_sending_video",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"endpoints_sending_audio\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "endpoints_sending_video" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "inactive_conferences",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"inactive_conferences\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "inactive_conferences" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "inactive_endpoints",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 2 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"inactive_conferences\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "inactive_endpoints" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "jitter_aggregate",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 2 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"jitter_aggregate\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "jitter_aggregate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "largest_conference",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 2 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"largest_conference\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "largest_conference" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "loss_rate_download",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 2 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"loss_rate_download\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "loss_rate_download" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "loss_rate_upload",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 2 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"loss_rate_download\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "loss_rate_upload" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "muc_clients_configured",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 2 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"muc_clients_configured\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "muc_clients_configured" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "muc_clients_connected",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"muc_clients_configured\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "muc_clients_connected" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "mucs_configured",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 4 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"mucs_configured\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "mucs_configured" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "mucs_joined",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 4 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"mucs_configured\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "mucs_joined" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "num_eps_no_msg_transport_after_delay",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 4 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"num_eps_no_msg_transport_after_delay\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "num_eps_no_msg_transport_after_delay"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "octo_conferences",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 4 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"num_eps_no_msg_transport_after_delay\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "octo_conferences" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "octo_endpoints",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 4 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"num_eps_no_msg_transport_after_delay\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "octo_endpoints" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "octo_receive_bitrate",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"octo_receive_bitrate\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "octo_receive_bitrate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "octo_receive_packet_rate",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"octo_receive_packet_rate\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "octo_receive_packet_rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "octo_send_bitrate",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"octo_send_bitrate\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "octo_send_bitrate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "octo_send_packet_rate",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"octo_send_packet_rate\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "octo_send_packet_rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "p2p_conferences",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"p2p_conferences\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "p2p_conferences" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "packet_rate_download",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"packet_rate_download\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "packet_rate_download" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "packet_rate_upload",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"packet_rate_download\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "packet_rate_upload" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "participants",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"packet_rate_download\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "participants" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "receive_only_endpoints",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"receive_only_endpoints\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "receive_only_endpoints" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "rtp_loss",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"receive_only_endpoints\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "rtp_loss" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "rtt_aggregate",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"rtt_aggregate\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "rtt_aggregate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "threads",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"rtt_aggregate\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "total_bytes_received",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"total_bytes_received\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total_bytes_received" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "total_bytes_received_octo",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"total_bytes_received_octo\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total_bytes_received_octo" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "total_bytes_sent",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"total_bytes_received\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total_bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "total_bytes_sent_octo",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"total_bytes_received\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total_bytes_sent_octo" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "total_colibri_web_socket_messages_received",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"total_colibri_web_socket_messages_received\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "total_colibri_web_socket_messages_received"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "total_colibri_web_socket_messages_sent",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"total_colibri_web_socket_messages_received\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "total_colibri_web_socket_messages_sent"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "total_conference_seconds",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"total_conference_seconds\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total_conference_seconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "total_conferences_completed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"total_conferences_completed\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total_conferences_completed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "total_conferences_created",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"total_conferences_completed\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total_conferences_created" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "total_data_channel_messages_received",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"total_data_channel_messages_received\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "total_data_channel_messages_received"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "total_data_channel_messages_sent",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"total_data_channel_messages_received\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "total_data_channel_messages_sent"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "total_dominant_speaker_changes",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"total_dominant_speaker_changes\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total_dominant_speaker_changes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "total_failed_conferences",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"total_failed_conferences\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total_failed_conferences" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "total_ice_failed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"total_ice_failed\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total_ice_failed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "total_ice_succeeded",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"total_ice_failed\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total_ice_succeeded" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "total_ice_succeeded_relayed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"total_ice_failed\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total_ice_succeeded_relayed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "total_ice_succeeded_tcp",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"total_ice_failed\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total_ice_succeeded_tcp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "total_loss_controlled_participant_seconds",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"total_loss_controlled_participant_seconds\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "total_loss_controlled_participant_seconds"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "total_loss_degraded_participant_seconds",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"total_loss_degraded_participant_seconds\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "total_loss_degraded_participant_seconds"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "total_loss_limited_participant_seconds",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"total_loss_degraded_participant_seconds\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "total_loss_limited_participant_seconds"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "total_packets_dropped_octo",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"total_packets_dropped_octo\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total_packets_dropped_octo" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "total_packets_received",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"total_packets_received\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total_packets_received" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "total_packets_received_octo",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"total_packets_received\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total_packets_received_octo" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "total_packets_sent",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"total_packets_received\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total_packets_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "total_packets_sent_octo",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"total_packets_sent_octo\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total_packets_sent_octo" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "total_partially_failed_conferences",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"total_partially_failed_conferences\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "total_partially_failed_conferences"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "total_participants",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"total_participants\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total_participants" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "videochannels",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"total_participants\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "videochannels" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  },
  {
   "title": "videostreams",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitsi_stats",
     "query": "SELECT mean(\"total_participants\") FROM \"jitsi_stats\" WHERE (\"host\" = 'jitsi_host') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "videostreams" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "jitsi_host" }
     ]
    }
   ]
  }
 ]
}